### ISSUE TITLE
Locale requirement

### ISSUE THREAD

**Issue by glensc** [smarbaa/yt-dlp-ugly-err#3]
```
$ yt-dlp https://r2.err.ee/1609329185/metallion-simo-atso                                                    
ERROR: unsupported locale setting
```

seems you have hardcoded locale requirement of `et_EE.UTF-8`:

```
$ LC_ALL=C ./yt-dlp.sh https://r2.err.ee/1609329185/metallion-simo-atso -v
[debug] Command-line config: ['https://r2.err.ee/1609329185/metallion-simo-atso', '-v']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.11.2 (CPython aarch64 64bit) - Linux-6.6.20+rpt-rpi-2712-aarch64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.40.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Extractor Plugins: UglyERRArhiivIE, UglyERRJupiterIE, UglyERRNewsIE, UglyERRRadioIE, UglyERRTVIE
[debug] Plugin directories: ['/lib/python3.11/site-packages/yt_dlp_plugins']
[debug] Loaded 1803 extractors
ERROR: unsupported locale setting
Traceback (most recent call last):
  File "/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1722, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    self.initialize()
  File "/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 624, in initialize
    self._real_initialize()
  File "/lib/python3.11/site-packages/yt_dlp_plugins/extractor/uglyerr.py", line 496, in _real_initialize
    super(_UglyERRLoginIE, self)._real_initialize()
  File "/lib/python3.11/site-packages/yt_dlp_plugins/extractor/uglyerr.py", line 172, in _real_initialize
    locale.setlocale(locale.LC_TIME, 'et_EE.UTF-8')
  File "/usr/lib/python3.11/locale.py", line 626, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting
```

**Comment by glensc** [comment]
instructions for debian can be found from here:

- https://wiki.debian.org/Locale

which is basically:
```sh
echo "et_EE.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
sudo locale-gen
```

**Comment by smarbaa** [comment]
I don't get what you mean by these instructions for Debian etc.

Setting locale the way it is done was necessary for parsing some dates in Estonian, if I remember it correctly. 
As it, indeed, cannot be relied on that the locale 'et_EE.UTF-8' is installed at the system level, I have to think of some other way to solve the problem.

Thanks!

**Comment by glensc** [comment]
My point was that if you put to readme instructions locale requirement, then that's an example how to install the needed locale on a Debian system.

**Comment by smarbaa** [comment]
Ok. Now I see.
Anyway, I decided to get rid of the locale requirement altogether.
